/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hesilfarma;

import DAO.ClientesDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.Cliente;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;


/**
 *
 * @author jhanc
 */
public class Clientes extends javax.swing.JPanel {
     private int idSeleccionado = 0;

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        jtableClientes.setDefaultEditor(Object.class, null);
        listarClientes();
        mostrarTotalClientes();
        jtableClientes.setRowHeight(24);

        jtableClientes.getTableHeader().setBackground(new Color(30,78,160));
        jtableClientes.getTableHeader().setForeground(Color.WHITE);
        jtableClientes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));

        jtableClientes.setSelectionBackground(new Color(180,220,255));
        jtableClientes.setSelectionForeground(Color.BLACK);
        personalizarTabla();
        ocultarColumnas();
        centrarColumnas();
       
    }
    private void listarClientes() 
    {

        DefaultTableModel modelo =(DefaultTableModel) jtableClientes.getModel();

        modelo.setRowCount(0);

        ClientesDAO dao = new ClientesDAO();

        List<Cliente> lista = dao.listar();

        for (Cliente clie : lista) 
        {

            Object[] fila = 
            {
                clie.getID_Cliente(),
                clie.getDNI(),
                clie.getNombre(),
                clie.getTelefono(),
                clie.getEstado()
                
            };

            modelo.addRow(fila);
        }
    }
    
    private void ocultarColumnas()
    {
        jtableClientes.setDefaultEditor(Object.class, null);
        
        jtableClientes.getColumnModel().getColumn(4).setMinWidth(0);
        jtableClientes.getColumnModel().getColumn(4).setMaxWidth(0);
        jtableClientes.getColumnModel().getColumn(4).setPreferredWidth(0);
        
        jtableClientes.getColumnModel().getColumn(0).setMinWidth(0);
        jtableClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtableClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        
    }
    private void Limpiar()
    {
        txtDNI.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDNI.requestFocus();
        idSeleccionado = 0;
        txtDNI.setEditable(true);
    }
    private void personalizarTabla()
    {
        JTableHeader header =jtableClientes.getTableHeader();

        header.setDefaultRenderer(new DefaultTableCellRenderer()
            {
                @Override
                public java.awt.Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,boolean hasFocus,int row,int column)
                {
                    JLabel lbl =(JLabel) super.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,column);

                    lbl.setBackground(new Color(32,72,140));

                    lbl.setForeground(Color.WHITE);

                    lbl.setFont(new Font("Segoe UI",Font.BOLD,13));

                    lbl.setHorizontalAlignment(SwingConstants.CENTER);

                    lbl.setOpaque(true);

                    return lbl;
                }
            });

        jtableClientes.setRowHeight(28);

        jtableClientes.setFont( new Font("Segoe UI",Font.PLAIN,12));

        jtableClientes.setSelectionBackground(new Color(52,152,219));

        jtableClientes.setSelectionForeground(Color.WHITE);

        jtableClientes.setShowVerticalLines(false);

        jtableClientes.setGridColor(new Color(220,220,220));
    }
        public void mostrarTotalClientes() 
        {

        ClientesDAO dao = new ClientesDAO();

        int total = dao.contarClientes();

        lbltotal.setText(String.valueOf(total));

        }
        public void centrarColumnas()
        {
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

            for (int i = 0; i < jtableClientes.getColumnCount(); i++) 
            {
                jtableClientes.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableClientes = new javax.swing.JTable();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();

        setForeground(new java.awt.Color(241, 248, 241));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(241, 248, 241));
        jPanel1.setForeground(new java.awt.Color(153, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 177, 76));
        jLabel2.setText("CLIENTES");

        jLabel3.setBackground(new java.awt.Color(30, 78, 160));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 78, 160));
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 78, 160));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 78, 160));
        jLabel5.setText("Telefono:");

        btnGuardar.setBackground(new java.awt.Color(70, 230, 120));
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(70, 170, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jtableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "DNI", "Nombre", "Telefono", "Estado"
            }
        ));
        jtableClientes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jtableClientes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableClientes);

        txtDNI.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 90, 90));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 78, 160));
        jLabel1.setText("Buscar Cliente:");

        btnLimpiar.setBackground(new java.awt.Color(80, 170, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 78, 160));
        jLabel6.setText("CLIENTES REGISTRADOS:");

        lbltotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(34, 177, 76));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbltotal))
                .addGap(48, 48, 48))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      try
      {
        if(txtDNI.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingresar DNI");
            return;
        }
        if(txtNombre.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Ingresar Nombre");
             return;
        }
        if(txtTelefono.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingrese número telefonico");
            return;
        }
        if(!txtDNI.getText().trim().matches("\\d{8}"))
        {
            JOptionPane.showMessageDialog(null,
                    "El DNI debe tener 8 dígitos");
            return;
        }
        if(!txtNombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))
        {
            JOptionPane.showMessageDialog(null,
                    "El nombre solo debe contener letras");
            return;
        }
        if(!txtTelefono.getText().trim().matches("\\d{9}"))
        {
            JOptionPane.showMessageDialog(null,
                    "El teléfono debe tener 9 dígitos");
            return;
        }
        
        Cliente clie = new Cliente();
        clie.setDNI(txtDNI.getText().trim());
        clie.setNombre(txtNombre.getText().trim());
        clie.setTelefono(txtTelefono.getText().trim());
        ClientesDAO dao = new ClientesDAO();
        if(dao.existeDNI(txtDNI.getText().trim()))
         {
             JOptionPane.showMessageDialog(null,"El DNI ya se encuentra registrado");
             return;
         }
         if(dao.guardar(clie))
         {
             JOptionPane.showMessageDialog( null,"Cliente registrado correctamente");
             listarClientes();
             mostrarTotalClientes();
             Limpiar();    

         }else
         {
             JOptionPane.showMessageDialog( null,"Error al registrar cliente");
         } 
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"Error inesperado: " + e.getMessage());
      } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableClientesMouseClicked
        int fila = jtableClientes.getSelectedRow();
        idSeleccionado = Integer.parseInt(jtableClientes.getValueAt(fila,0).toString());
        txtDNI.setText(jtableClientes.getValueAt(fila,1).toString());
        txtNombre.setText(jtableClientes.getValueAt(fila,2).toString());
        txtTelefono.setText(jtableClientes.getValueAt(fila,3).toString());
        txtDNI.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableClientesMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try
        {
            if(idSeleccionado == 0)
            {
                JOptionPane.showMessageDialog(null,"Seleccione un cliente");
                return;
            }
             if(txtDNI.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog( null,"Ingrese el DNI");
                return;
            }

            if(txtNombre.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Ingrese el nombre");
                return;
            }

            if(txtTelefono.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog( null,"Ingrese número de Telefono");
                return;
            }
            if(!txtDNI.getText().trim().matches("\\d{8}"))
            {
                JOptionPane.showMessageDialog(null,
                        "El DNI debe tener 8 dígitos");
                return;
            }

            if(!txtNombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))
            {
                JOptionPane.showMessageDialog(null,
                        "El nombre solo debe contener letras");
                return;
            }

            if(!txtTelefono.getText().trim().matches("\\d{9}"))
            {
                JOptionPane.showMessageDialog(null,
                        "El teléfono debe tener 9 dígitos");
                return;
            }

            Cliente clie = new Cliente();

            clie.setID_Cliente(idSeleccionado);
            clie.setDNI(txtDNI.getText().trim());
            clie.setNombre(txtNombre.getText().trim());
            clie.setTelefono(txtTelefono.getText().trim());
            ClientesDAO dao = new ClientesDAO();
            if(dao.actualizar(clie))
            {
                JOptionPane.showMessageDialog(null,"Cliente actualizado correctamente");

                listarClientes();
                Limpiar();

            }
            else
            {
                JOptionPane.showMessageDialog( null,"No se pudo actualizar");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error inesperado: " + e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(idSeleccionado == 0)
        {
            JOptionPane.showMessageDialog( null,"Seleccione un Cliente");
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Desea eliminar a este Cliente?","Confirmar eliminación", JOptionPane.YES_NO_OPTION);
       if(respuesta == JOptionPane.YES_OPTION)
       {
           ClientesDAO clie = new ClientesDAO();
           if(clie.eliminar(idSeleccionado))
           {
               JOptionPane.showMessageDialog( null,"Cliente eliminado");
               listarClientes();
               mostrarTotalClientes();
               Limpiar();
           }else
           {
               JOptionPane.showMessageDialog(null,"No se pudo eliminar");
           }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
        jtableClientes.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }

        if(txtTelefono.getText().length() >= 9)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)&& c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }

        if(txtDNI.getText().length() >= 8)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String nombre =txtBuscar.getText().trim();
        ClientesDAO dao = new ClientesDAO();
        List<Cliente> lista = dao.buscarClienteDinac(nombre);
        DefaultTableModel modelo = (DefaultTableModel)jtableClientes.getModel();
        modelo.setRowCount(0);
        for(Cliente cli : lista)
        {
             modelo.addRow(new Object[]
        {
            cli.getID_Cliente(),
            cli.getDNI(),
            cli.getNombre(),
            cli.getTelefono()
        });
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)
                && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableClientes;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
