/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hesilfarma;

import DAO.ClientesDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.Cliente;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author jhanc
 */
public class Clientes extends javax.swing.JPanel {
     private int idSeleccionado = 0;

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        jtableClientes.setDefaultEditor(Object.class, null);
        listarClientes();
    }
    private void listarClientes() {

        DefaultTableModel modelo =(DefaultTableModel) jtableClientes.getModel();

        modelo.setRowCount(0);

        ClientesDAO dao = new ClientesDAO();

        List<Cliente> lista = dao.listar();

        for (Cliente clie : lista) 
        {

            Object[] fila = 
            {
                clie.getID_Cliente(),
                clie.getDNI(),
                clie.getNombre(),
                clie.getTelefono()
                
            };

            modelo.addRow(fila);
        }
    }
    private void Limpiar()
    {
        txtDNI.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDNI.requestFocus();
        idSeleccionado = 0;
        txtDNI.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableClientes = new javax.swing.JTable();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaBuscar = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 102));
        jLabel2.setText("CLIENTES");

        jLabel3.setText("DNI:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Telefono:");

        btnGuardar.setText("REGISTRAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jtableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "DNI", "Nombre", "Telefono"
            }
        ));
        jtableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableClientes);

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel1.setText("Buscar Cliente");

        txtBuscar.setText("Ingresar DNI");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        areaBuscar.setColumns(20);
        areaBuscar.setRows(5);
        jScrollPane2.setViewportView(areaBuscar);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      try
      {
        if(txtDNI.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingresar DNI");
            return;
        }
        if(txtNombre.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Ingresar Nombre");
             return;
        }
        if(txtTelefono.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingrese número telefonico");
            return;
        }
        if(!txtDNI.getText().trim().matches("\\d{8}"))
        {
            JOptionPane.showMessageDialog(null,
                    "El DNI debe tener 8 dígitos");
            return;
        }
        if(!txtNombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))
        {
            JOptionPane.showMessageDialog(null,
                    "El nombre solo debe contener letras");
            return;
        }
        if(!txtTelefono.getText().trim().matches("\\d{9}"))
        {
            JOptionPane.showMessageDialog(null,
                    "El teléfono debe tener 9 dígitos");
            return;
        }
        
        Cliente clie = new Cliente();
        clie.setDNI(txtDNI.getText().trim());
        clie.setNombre(txtNombre.getText().trim());
        clie.setTelefono(txtTelefono.getText().trim());
        ClientesDAO dao = new ClientesDAO();
        if(dao.existeDNI(txtDNI.getText().trim()))
         {
             JOptionPane.showMessageDialog(null,"El DNI ya se encuentra registrado");
             return;
         }
         if(dao.guardar(clie))
         {
             JOptionPane.showMessageDialog( null,"Cliente registrado correctamente");
             listarClientes();
             Limpiar();    

         }else
         {
             JOptionPane.showMessageDialog( null,"Error al registrar cliente");
         } 
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"Error inesperado: " + e.getMessage());
      } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableClientesMouseClicked
        int fila = jtableClientes.getSelectedRow();
        idSeleccionado = Integer.parseInt(jtableClientes.getValueAt(fila,0).toString());
        txtDNI.setText(jtableClientes.getValueAt(fila,1).toString());
        txtNombre.setText(jtableClientes.getValueAt(fila,2).toString());
        txtTelefono.setText(jtableClientes.getValueAt(fila,3).toString());
        txtDNI.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableClientesMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try
        {
            if(idSeleccionado == 0)
            {
                JOptionPane.showMessageDialog(null,"Seleccione un cliente");
                return;
            }
             if(txtDNI.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog( null,"Ingrese el DNI");
                return;
            }

            if(txtNombre.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Ingrese el nombre");
                return;
            }

            if(txtTelefono.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog( null,"Ingrese número de Telefono");
                return;
            }
            if(!txtDNI.getText().trim().matches("\\d{8}"))
            {
                JOptionPane.showMessageDialog(null,
                        "El DNI debe tener 8 dígitos");
                return;
            }

            if(!txtNombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))
            {
                JOptionPane.showMessageDialog(null,
                        "El nombre solo debe contener letras");
                return;
            }

            if(!txtTelefono.getText().trim().matches("\\d{9}"))
            {
                JOptionPane.showMessageDialog(null,
                        "El teléfono debe tener 9 dígitos");
                return;
            }

            Cliente clie = new Cliente();

            clie.setID_Cliente(idSeleccionado);
            clie.setDNI(txtDNI.getText().trim());
            clie.setNombre(txtNombre.getText().trim());
            clie.setTelefono(txtTelefono.getText().trim());
            ClientesDAO dao = new ClientesDAO();
            if(dao.actualizar(clie))
            {
                JOptionPane.showMessageDialog(null,"Cliente actualizado correctamente");

                listarClientes();
                Limpiar();

            }
            else
            {
                JOptionPane.showMessageDialog( null,"No se pudo actualizar");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error inesperado: " + e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(idSeleccionado == 0)
        {
            JOptionPane.showMessageDialog( null,"Seleccione un Cliente");
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Desea eliminar a este Cliente?","Confirmar eliminación", JOptionPane.YES_NO_OPTION);
       if(respuesta == JOptionPane.YES_OPTION)
       {
           ClientesDAO clie = new ClientesDAO();
           if(clie.eliminar(idSeleccionado))
           {
               JOptionPane.showMessageDialog( null,"Cliente eliminado");
               listarClientes();
               Limpiar();
           }else
           {
               JOptionPane.showMessageDialog(null,"No se pudo eliminar");
           }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        txtBuscar.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try
        {
        String dni = txtBuscar.getText().trim();
        if(!dni.matches("\\d{8}"))
        {
            JOptionPane.showMessageDialog(null,"Ingrese un DNI válido");
            return;
        }
        ClientesDAO dao = new ClientesDAO();
        Cliente cli = dao.buscarCliente(dni);
        if(cli != null)
        {
            areaBuscar.setText("DNI: " + cli.getDNI()
                               +"\nNombre: " + cli.getNombre()
                               +"\nTeléfono: " + cli.getTelefono());
        }else
        {
            areaBuscar.setText("Cliente no registrado");
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al buscar: " + e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
        areaBuscar.setText("");
        txtBuscar.setText("");
        jtableClientes.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }

        if(txtBuscar.getText().length() >= 8)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }

        if(txtTelefono.getText().length() >= 9)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)
                && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }

        if(txtDNI.getText().length() >= 8)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaBuscar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtableClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
