/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hesilfarma;

import DAO.reportesDAO;
import Modelo.reporte;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import javax.swing.JFileChooser;

/**
 *
 * @author jhanc
 */
public class reportes extends javax.swing.JPanel {

    /**
     * Creates new form reportes
     */
    public reportes() {
        
        initComponents();
        cargarEstadisticas();
       
    }
    private void cargarEstadisticas()
    {
        reportesDAO dao =new reportesDAO();

        lblTotalVentas.setText("S/. "+ String.format("%.2f",dao.totalVentas()));

        lblProductosVendidos.setText(String.valueOf(dao.productosVendidos()));

        lblNumeroVentas.setText(String.valueOf(dao.numeroVentas()));

        txtmedicamento.setText(dao.medicamentoMasVendido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExportarPdf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        lblProductosVendidos = new javax.swing.JLabel();
        lblNumeroVentas = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtskere = new javax.swing.JLabel();
        txtmedicamento = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Medicamento", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        jLabel1.setText("Fecha Inicio");

        jLabel2.setText("Fechan fin");

        btnExportarPdf.setText("EXPORTAR PDF");
        btnExportarPdf.addActionListener(this::btnExportarPdfActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total Ventas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Productos Vendidos:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N* ventas:");

        lblTotalVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalVentas.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalVentas.setText("0.0");

        lblProductosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductosVendidos.setForeground(new java.awt.Color(0, 0, 0));
        lblProductosVendidos.setText("0.0");

        lblNumeroVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroVentas.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroVentas.setText("0.0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("REPORTES");

        txtskere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtskere.setForeground(new java.awt.Color(0, 0, 0));
        txtskere.setText("Medicamento más vendido:");

        txtmedicamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmedicamento.setForeground(new java.awt.Color(0, 0, 0));
        txtmedicamento.setText("-");

        btnMostrar.setText("MOSTRAR ");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar)
                                .addGap(13, 13, 13)
                                .addComponent(btnExportarPdf))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(26, 26, 26)
                                    .addComponent(fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroVentas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalVentas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProductosVendidos))
                            .addComponent(txtmedicamento)
                            .addComponent(txtskere))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPdf)
                    .addComponent(btnMostrar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblProductosVendidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNumeroVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtskere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmedicamento)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
      try
      {
        DefaultTableModel modelo =(DefaultTableModel)tablaReportes.getModel();
        modelo.setRowCount(0);
        reportesDAO dao = new reportesDAO();

        List<reporte> lista = dao.listarVentas();
          for (reporte rep : lista)
          {
              modelo.addRow(new Object[]
              {
                  rep.getFecha(),
                  rep.getCliente(),
                  rep.getMedicamento(),
                  rep.getCantidad(),
                  rep.getPrecio(),
                  rep.getSubtotal()
              });
          }
          cargarEstadisticas();
          fechaInicio.setDate(null);
          fechaFin.setDate(null);
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"Error al mostrar reportes: "+ e.getMessage());
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
       try
       {
            if(fechaInicio.getDate() == null || fechaFin.getDate() == null)
            {
                JOptionPane.showMessageDialog(null,"Seleccione ambas fechas");
                return;
            }
            if(fechaInicio.getDate().after(fechaFin.getDate()))
            {
                JOptionPane.showMessageDialog(null,"La fecha inicial no puede ser mayor que la fecha final");
                return;
            }

            java.sql.Date inicio =new java.sql.Date(fechaInicio.getDate().getTime());

            java.sql.Date fin =new java.sql.Date(fechaFin.getDate().getTime());

            reportesDAO dao =new reportesDAO();

            List<reporte> lista =dao.buscarPorFechas(inicio,fin);

            DefaultTableModel modelo =(DefaultTableModel)tablaReportes.getModel();

            modelo.setRowCount(0);
            if(lista.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"No existen ventas en ese rango de fechas");
            }

            for(reporte rep : lista)
            {
                modelo.addRow(new Object[]
                {
                    rep.getFecha(),
                    rep.getCliente(),
                    rep.getMedicamento(),
                    rep.getCantidad(),
                    rep.getPrecio(),
                    rep.getSubtotal()
                });
            }
            lblTotalVentas.setText("S/. "+ String.format("%.2f",dao.totalVentasPorFecha(inicio,fin)));

            lblProductosVendidos.setText(String.valueOf(dao.productosVendidosPorFecha(inicio,fin)));

            lblNumeroVentas.setText(String.valueOf(dao.numeroVentasPorFecha(inicio,fin)));

            txtmedicamento.setText(dao.medicamentoMasVendidoPorFecha(inicio,fin));
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,"Error al generar reporte: "+ e.getMessage());
       }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfActionPerformed
        try
        {
            JFileChooser chooser = new JFileChooser();

            chooser.setSelectedFile(new File("ReporteVentas.pdf"));

            int opcion = chooser.showSaveDialog(this);

            if(opcion != JFileChooser.APPROVE_OPTION)
            {
                return;
            }

            Document documento = new Document();

            PdfWriter.getInstance(documento,new FileOutputStream(chooser.getSelectedFile()));

            documento.open();

            documento.add(new Paragraph("REPORTE DE VENTAS"));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Fecha: " + LocalDate.now()));
            documento.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(6);

            tabla.addCell("Fecha");
            tabla.addCell("Cliente");
            tabla.addCell("Medicamento");
            tabla.addCell("Cantidad");
            tabla.addCell("Precio");
            tabla.addCell("Subtotal");

            for(int i = 0; i < tablaReportes.getRowCount(); i++)
            {
                tabla.addCell(tablaReportes.getValueAt(i,0).toString());
                tabla.addCell(tablaReportes.getValueAt(i,1).toString());
                tabla.addCell(tablaReportes.getValueAt(i,2).toString());
                tabla.addCell(tablaReportes.getValueAt(i,3).toString());
                tabla.addCell(tablaReportes.getValueAt(i,4).toString());
                tabla.addCell(tablaReportes.getValueAt(i,5).toString());
            }

            documento.add(tabla);

            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Total Ventas: " + lblTotalVentas.getText()));
            documento.add(new Paragraph("Productos Vendidos: " + lblProductosVendidos.getText()));
            documento.add(new Paragraph("Numero de Ventas: " + lblNumeroVentas.getText()));
            documento.add(new Paragraph("Medicamento mas vendido: " + txtmedicamento.getText()));

            documento.close();

            JOptionPane.showMessageDialog(null,"PDF generado correctamente");
            Desktop.getDesktop().open(chooser.getSelectedFile());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportarPdf;
    private javax.swing.JButton btnMostrar;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroVentas;
    private javax.swing.JLabel lblProductosVendidos;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JTable tablaReportes;
    private javax.swing.JLabel txtmedicamento;
    private javax.swing.JLabel txtskere;
    // End of variables declaration//GEN-END:variables
}
