/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hesilfarma;

import DAO.reportesDAO;
import Modelo.reporte;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import com.itextpdf.text.Font;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;

/**
 *
 * @author jhanc
 */
public class reportes extends javax.swing.JPanel {

    /**
     * Creates new form reportes
     */
    public reportes() {
        
        initComponents();
        personalizarTabla();
        ((JTextField) fechaInicio.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField) fechaFin.getDateEditor().getUiComponent()).setEditable(false);
        DefaultTableModel modelo = (DefaultTableModel) tablaReportes.getModel();
        modelo.setRowCount(0);
        limpiarEstadisticas();
       
    }
    private void cargarEstadisticas()
    {
        reportesDAO dao =new reportesDAO();

        lblTotalVentas.setText("S/. "+ String.format("%.2f",dao.totalVentas()));

        lblProductosVendidos.setText(String.valueOf(dao.productosVendidos()));

        lblNumeroVentas.setText(String.valueOf(dao.numeroVentas()));

        txtmedicamento.setText(dao.medicamentoMasVendido());
    }
    private void limpiarEstadisticas()
    {
        lblTotalVentas.setText("S/. 0.00");
        lblProductosVendidos.setText("0");
        lblNumeroVentas.setText("0");
        txtmedicamento.setText("-");
    }
    private void personalizarTabla()
    {
        JTableHeader header =tablaReportes.getTableHeader();

        header.setDefaultRenderer(new DefaultTableCellRenderer()
            {
                @Override
                public java.awt.Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,boolean hasFocus,int row,int column)
                {
                    JLabel lbl =(JLabel) super.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,column);

                    lbl.setBackground(new Color(32,72,140));

                    lbl.setForeground(Color.WHITE);


                    lbl.setHorizontalAlignment(SwingConstants.CENTER);

                    lbl.setOpaque(true);

                    return lbl;
                }
            });

        tablaReportes.setRowHeight(28);

        tablaReportes.setSelectionBackground(new Color(52,152,219));

        tablaReportes.setSelectionForeground(Color.WHITE);

        tablaReportes.setShowVerticalLines(false);

        tablaReportes.setGridColor(new Color(220,220,220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExportarPdf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        lblProductosVendidos = new javax.swing.JLabel();
        lblNumeroVentas = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtskere = new javax.swing.JLabel();
        txtmedicamento = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setBackground(new java.awt.Color(236, 245, 236));
        jPanel1.setForeground(new java.awt.Color(236, 245, 236));

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Medicamento", "Categoría", "Cantidad", "PrecioUnitario", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);
        if (tablaReportes.getColumnModel().getColumnCount() > 0) {
            tablaReportes.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(32, 72, 140));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 72, 140));
        jLabel1.setText("Fecha Inicio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 72, 140));
        jLabel2.setText("Fechan fin");

        btnExportarPdf.setBackground(new java.awt.Color(220, 70, 70));
        btnExportarPdf.setText("EXPORTAR PDF");
        btnExportarPdf.addActionListener(this::btnExportarPdfActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 72, 140));
        jLabel3.setText("Total Ventas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 72, 140));
        jLabel4.setText("Productos Vendidos:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 72, 140));
        jLabel5.setText("N* ventas:");

        lblTotalVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalVentas.setForeground(new java.awt.Color(34, 177, 76));
        lblTotalVentas.setText("0.0");

        lblProductosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProductosVendidos.setForeground(new java.awt.Color(34, 177, 76));
        lblProductosVendidos.setText("0.0");

        lblNumeroVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumeroVentas.setForeground(new java.awt.Color(34, 177, 76));
        lblNumeroVentas.setText("0.0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(39, 174, 96));
        jLabel9.setText("REPORTES");

        txtskere.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtskere.setForeground(new java.awt.Color(32, 72, 140));
        txtskere.setText("Medicamento más vendido:");

        txtmedicamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtmedicamento.setForeground(new java.awt.Color(34, 177, 76));
        txtmedicamento.setText("-");

        btnMostrar.setBackground(new java.awt.Color(70, 230, 120));
        btnMostrar.setText("MOSTRAR ");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(70, 170, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(26, 26, 26)
                                    .addComponent(fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnBuscar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMostrar)
                                    .addGap(13, 13, 13)
                                    .addComponent(btnExportarPdf)))
                            .addComponent(jLabel5)
                            .addComponent(lblProductosVendidos)
                            .addComponent(lblNumeroVentas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTotalVentas))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtskere)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmedicamento)
                                .addGap(112, 112, 112))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPdf)
                    .addComponent(btnMostrar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtskere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalVentas)
                    .addComponent(txtmedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductosVendidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroVentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
      try
      {
        DefaultTableModel modelo =(DefaultTableModel)tablaReportes.getModel();
        modelo.setRowCount(0);
        reportesDAO dao = new reportesDAO();
        List<reporte> lista = dao.listarVentas();
          for (reporte rep : lista)
          {
              modelo.addRow(new Object[]
              {
                  rep.getFecha(),
                  rep.getCliente(),
                  rep.getMedicamento(),
                  rep.getCategoria(),
                  rep.getCantidad(),
                  rep.getPrecio(),
                  rep.getSubtotal()
              });
          }
          cargarEstadisticas();
          fechaInicio.setDate(null);
          fechaFin.setDate(null);
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"Error al mostrar reportes: "+ e.getMessage());
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
       try
       {
            if(fechaInicio.getDate() == null || fechaFin.getDate() == null)
            {
                JOptionPane.showMessageDialog(null,"Seleccione ambas fechas");
                return;
            }
            if(fechaInicio.getDate().after(fechaFin.getDate()))
            {
                JOptionPane.showMessageDialog(null,"La fecha inicial no puede ser mayor que la fecha final");
                return;
            }

            java.sql.Date inicio =new java.sql.Date(fechaInicio.getDate().getTime());

            java.sql.Date fin =new java.sql.Date(fechaFin.getDate().getTime());

            reportesDAO dao =new reportesDAO();

            List<reporte> lista =dao.buscarPorFechas(inicio,fin);

            DefaultTableModel modelo =(DefaultTableModel)tablaReportes.getModel();

            modelo.setRowCount(0);
            if(lista.isEmpty())
            {
                modelo.setRowCount(0);
                limpiarEstadisticas();
                JOptionPane.showMessageDialog(null,"No existen ventas en ese rango de fechas.");
                return;
            }

            for(reporte rep : lista)
            {
                modelo.addRow(new Object[]
                {
                    rep.getFecha(),
                    rep.getCliente(),
                    rep.getMedicamento(),
                    rep.getCategoria(),
                    rep.getCantidad(),
                    rep.getPrecio(),
                    rep.getSubtotal()
                });
            }
            lblTotalVentas.setText("S/. "+ String.format("%.2f",dao.totalVentasPorFecha(inicio,fin)));

            lblProductosVendidos.setText(String.valueOf(dao.productosVendidosPorFecha(inicio,fin)));

            lblNumeroVentas.setText(String.valueOf(dao.numeroVentasPorFecha(inicio,fin)));

            txtmedicamento.setText(dao.medicamentoMasVendidoPorFecha(inicio,fin));
            fechaInicio.setDate(null);
            fechaFin.setDate(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,"Error al generar reporte: "+ e.getMessage());
       }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaReportes.getModel();

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,"Primero debe mostrar o buscar los reportes antes de exportar el PDF.","Sin datos",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try
        {
            JFileChooser chooser = new JFileChooser();

            chooser.setSelectedFile(new File("ReporteVentas.pdf"));

            int opcion = chooser.showSaveDialog(this);

            if(opcion != JFileChooser.APPROVE_OPTION)
            {
                return;
            }

            Document documento = new Document();

            PdfWriter.getInstance(documento,new FileOutputStream(chooser.getSelectedFile()));

            documento.open();

            Font titulo = new Font(Font.FontFamily.HELVETICA,18,Font.BOLD,BaseColor.BLUE);
            Paragraph encabezado = new Paragraph("REPORTE DE VENTAS",titulo);
            encabezado.setAlignment(Element.ALIGN_CENTER);

            documento.add(encabezado);
            documento.add(new Paragraph(" "));

            Paragraph fecha = new Paragraph("Fecha de generación: " + LocalDate.now());
            fecha.setAlignment(Element.ALIGN_RIGHT);

            documento.add(fecha);
            documento.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(7);
            tabla.setWidthPercentage(100);
            tabla.setSpacingBefore(10f);
            tabla.setSpacingAfter(10f);

            PdfPCell celda;

            celda = new PdfPCell(new Phrase("Fecha"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Cliente"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Medicamento"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Categoría"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Cantidad"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Precio"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);

            celda = new PdfPCell(new Phrase("Subtotal"));
            celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(celda);
            
            for(int i = 0; i < tablaReportes.getRowCount(); i++)
            {
                
                for(int j = 0; j < 7; j++)
                {
                    PdfPCell dato = new PdfPCell(new Phrase(tablaReportes.getValueAt(i,j).toString()));
                    dato.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(dato);
                }
            }

            documento.add(tabla);

            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("=============================================="));

            Font negrita = new Font(Font.FontFamily.HELVETICA,12,Font.BOLD);

            documento.add(new Paragraph("Total de Ventas: " + lblTotalVentas.getText(),negrita));
            documento.add(new Paragraph("Productos Vendidos: " + lblProductosVendidos.getText(),negrita));
            documento.add(new Paragraph("Número de Ventas: " + lblNumeroVentas.getText(),negrita));
            documento.add(new Paragraph("Medicamento Más Vendido: " + txtmedicamento.getText(),negrita));

            documento.close();

            JOptionPane.showMessageDialog(null,"PDF generado correctamente");
            Desktop.getDesktop().open(chooser.getSelectedFile());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportarPdf;
    private javax.swing.JButton btnMostrar;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroVentas;
    private javax.swing.JLabel lblProductosVendidos;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JTable tablaReportes;
    private javax.swing.JLabel txtmedicamento;
    private javax.swing.JLabel txtskere;
    // End of variables declaration//GEN-END:variables
}
